GET http://localhost:3001/ingressos


###
POST http://localhost:3001/ingressos/
Content-Type: application/json

{
    "jogo": "Flamengo x Athletic",
    "preco": 150,
    "setor": "Arquibancada"
}


###
GET http://localhost:3001/ingressos/4


###
PUT http://localhost:3001/ingressos/4
Content-Type: application/json

{
    "jogo": "Flamengo x Athletic",
    "preco": 150,
    "setor": "Arquibancada"
}


###
DELETE http://localhost:3001/ingressos/4



 
